### ISSUE TITLE
WCAG AA Fix: Update cookie banner message to be more descriptive

### ISSUE THREAD

**Issue by CarolineS-QA** [hmrc/tracking-consent-frontend#168]
### To do
Update `banner.confirmation.hide` to read as "Hide cookies message"

### Background
Our DAC audit has flagged this as a AA issue within our service, which uses the cookie banner implemented here. It is the same as the GDS implementation https://design-system.service.gov.uk/components/cookie-banner/ and we are aiming to raise this with them too.

### DAC Audit
Medium Priority WCAG Level AA
Non-Descriptive Form Elements
Form elements are present that are not descriptive of their function or purpose.

WCAG Reference:
2.4.6 Headings and Labels (Level AA)
Understanding Headings and Labels | How to Meet Headings and Labels
Issue ID: DAC_Non-Descriptive_Form_Elements_01

URL: https://www.staging.tax.service.gov.uk/agent-subscription/business-type
Page title: What type of business are you? - Create an agent services account - GOV.UK
Agent Subscription Journeys
Journey 1: Happy path
1. What type of business are you?
Screenshot: 
<img width="568" alt="Screenshot 2022-03-01 at 14 13 11" src="https://user-images.githubusercontent.com/62263396/156184955-97e9db74-fef8-4877-b73e-03a233ca45ef.png">

Original comment:
The ‘Hide this message’ button related to the Cookies banner is not descriptive enough for
screen reader users to determine its function or purpose when navigating out of context.
Retest comment:
This issue was still present on the page.

Current code ref(s):
body > div.cbanner-govuk-cookie-banner > div > div.cbanner-govuk-button-group > button
<button class="cbanner-govuk-button" data-module="cbanner-govuk-button">
 Hide this message
 </button>

Original Solution:
Ensure that all form elements are uniquely descriptive of their purpose. 

Retest Solution:
We would still recommend expanding on the Cookie message by describing to users what
will be hidden.
Example:
<button class="cbanner-govuk-button" data-module="cbanner-govuk-button">
Hide cookies message
</button>

**Comment by ellamdav** [comment]
This has been addressed by #174 - if the eventual GDS solution differs from this, we'll review and possibly re-align then.
